export const roomData = [
  {
    currentPlayer: '5',
    maxPlayer: '10',
    language: 'EN',
    point: '150',
    roomName: 'Room1',
    roomId: 'id1',
  },
  {
    currentPlayer: '10',
    maxPlayer: '15',
    language: 'VI',
    point: '70',
    roomName: 'Room2',
    roomId: 'id2',
  },
  {
    currentPlayer: '5',
    maxPlayer: '10',
    language: 'EN',
    point: '150',
    roomName: 'Room3',
    roomId: 'id3',
  },
  {
    currentPlayer: '5',
    maxPlayer: '10',
    language: 'EN',
    point: '150',
    roomName: 'Room4',
    roomId: 'id4',
  },
  {
    currentPlayer: '5',
    maxPlayer: '10',
    language: 'EN',
    point: '150',
    roomName: 'Room5',
    roomId: 'id5',
  },
  {
    currentPlayer: '5',
    maxPlayer: '10',
    language: 'EN',
    point: '150',
    roomName: 'Room6',
    roomId: 'id6',
  },
];
